### ISSUE TITLE
[ENHANCEMENT] My Feature Request : Thank you so much for your effort Mr Daniel. I hope if you could add a "Tab" for some old notations [ Oxia, isaki above and under the neumes, strepton, tromikon, ligizma, tsakizma, paraklitiki]. Another request: Is there any possibility to add an option for the double isokratima? Thank you 

### ISSUE THREAD

**Issue by Eliekhacho** [neanes/neanes#564] opened 2024-03-12 08:06 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by basil** [comment] 2024-03-12 16:50
Duplicate of #425.

**Closed by basil** 2024-03-12 16:50 UTC
Labels: enhancement
