### ISSUE TITLE
OCR recognition for regular Greek and English music byzantine texts

### ISSUE THREAD

**Issue by kostasfragkiadakis** [neanes/neanes#959] opened 2024-09-10 11:02 UTC
**Is your feature request related to a problem? Please describe.**
it would be quite helpful if you could build a capability to recognize Byzantine musical symbols from books  which would be automatically passed to the main program

from byzantine book with a ocr scanner to your main program

**Comment by basil** [comment] 2024-09-10 19:27
Duplicate of #195

**Closed** 2024-09-10 19:27 UTC
Labels: Type: Feature
