### ISSUE TITLE
[ISSUE] [Version 0.4.17] Ison playback not respecting Fthores/New Mode Keys

### ISSUE THREAD

**Issue by PeTH2** [neanes/neanes#528] opened 2024-03-09 22:27 UTC
Vou and Low Zo ison doesnt match the physical note and creates an out of place sound. Using the (M)/Μαζί ison marker works.

This occurs with transposition fthorai over any note that modifies the scale of the original note as well as Pl. 4 on Pa.

**To Reproduce**
Create new file

Set Mode Key as Pl 4 from Pa or add Ni Fthora to Pa.

Add and Oligon

Set Ison to Vou

Listen

**Expected behavior**
Ison Markings should match the note of the mode, as they would when you sing.

**Comment by danielgarthur** [comment] 2024-03-12 01:14
@basil Do you recall why `IsonNode` has no concept of virtual notes? It seems like the issue is that the `IsonNode` should have a virtual note of `Pa` and the playback would be corrected.

**Comment by basil** [comment] 2024-03-12 01:17
I was about to post a similar message. I agree that `IsonNode` should be switched to virtual notes.

**Comment by danielgarthur** [comment] 2024-03-12 03:36
Fixed in [0.4.18](https://github.com/neanes/neanes/releases/tag/v0.4.18).

**Closed by danielgarthur** 2024-03-12 03:36 UTC
Labels: bug
