### ISSUE TITLE
Multi-Line Lyrics

### ISSUE THREAD

**Issue by PeTH2** [neanes/neanes#706] opened 2024-05-22 08:05 UTC
Some scores, namely settings of the Δύναμις of the Trisagion, have multiple lines of lyrics under the same neumes to indicate either a repeat, or variable text that shares meter (ex. Σῶσον ἡμᾶς Υἱὲ Θεοῦ, **ὁ ἀναστὰς ἐκ νεκρῶν/ὁ ἐν ἁγίοις θαυμαστῶς** ψαλλοντὰς σοι Ἀλληλούϊα).

Would this be something that could be added?

**Comment by basil** [comment] 2024-05-22 14:22
Duplicate of #35

**Closed by basil** 2024-05-22 14:22 UTC
Labels: Type: Feature
