### ISSUE TITLE
Line margins changing back and forth while typing

### ISSUE THREAD

**Issue by pabaxe** [neanes/neanes#812] opened 2024-07-05 09:16 UTC
**This bug was found in**

- [x] Desktop
- [ ] Web App
- [ ] Both

**Describe the bug**
While writing a score, after a certain line was filled and the cursor went automatically to the next line, the margins of the line above change each time something is typed, and then changes back and forth continuously. I'm attaching a video to better describe it. 

In the video, all I'm doing is pressing (J) and deleting, to showcase the issue. 

**Screenshots or files**

https://github.com/neanes/neanes/assets/174416975/cd62c9e8-133f-4015-a36a-7efc15b905e6

**Desktop Version (please complete the following information, if applicable):**

- OS: MacOS Sonoma 14.5
- Version 0.4.45

**Comment by danielgarthur** [comment] 2024-07-05 15:42
@pabaxe Could you attach the file? You'll have to put it in a `zip` archive or Github won't let you upload it.

@basil The only thing that I can think of from the video is that the logic that automatically adds bar lines to the last neume in the previous line is adding the bar line, but that pushes the width of the line over the edge, so it breaks to a new line, and now no longer needs the bar, so now it can fit on the previous line again. And so the cycle goes back and forth.

**Comment by basil** [comment] 2024-07-05 16:05
Yeah, I've seen this problem in a lot of my own scores as well, and I've long suspected that what you described above is the root cause.

**Comment by pabaxe** [comment] 2024-07-05 16:09
Yes after messing around I found that the only way to bypass it is by removing the bar lines. Sometimes, if the bar line is double, making it single also works, but not always.

**Comment by danielgarthur** [comment] 2024-07-05 17:56
@pabaxe I've found a way to reliably reproduce this, so your file is not necessary.

**Comment by danielgarthur** [comment] 2024-07-06 01:03
Fixed in [0.4.46](https://github.com/neanes/neanes/releases/tag/v0.4.46)

**Closed by danielgarthur** 2024-07-06 01:03 UTC
Labels: Type: Bug, Component: Layout
