### ISSUE TITLE
OCR feature

### ISSUE THREAD

**Issue by dimii27** [neanes/neanes#776] opened 2024-06-22 23:06 UTC
Is there any way to use OCR to scan a .pdf so that it can be played back with neanes? (or BZQ)

[This](https://github.com/user-attachments/files/15941989/Exerci.ii.psaltice.anul.II.Pastorala.pdf) is the document I'm studying and I would like to convert it into .byz by using my computer to do it for me so I can focus on studying rather than imputing it manually. Is there any other quick way (until june 27th) to "listen" to this fast using computers or is it not developed yet?

**Comment by basil** [comment] 2024-06-23 00:33
Duplicate of #195

**Closed by basil** 2024-06-23 00:33 UTC
Labels: Type: Feature
