### ISSUE TITLE
Playback of petasti

### ISSUE THREAD

**Issue by mattsmi** [neanes/neanes#616] opened 2024-04-11 08:48 UTC
**Is your feature request related to a problem? Please describe.**
Currently, Neanes plays back a petasti as if it were an oligon: i.e. one step up from the previous note, but with no ornamentation or qualitative aspect.

**Describe the solution you'd like**
Play the petasti back, as it would be sung: break the note into quarters all slurred together, the first quarter is on the base note, the second quarter ascends one note higher returning to the base note for the latter two quarters. This corresponds with what we are taught by our patriarchal protopsaltis and how he teaches the petasti as well.

**Additional context**
St Anthony's monastery seems to define a petasti as an acciaccatura (grace note) between two quavers (eighth notes in the US). In musical theory, we consider an acciaccatura as taking 1/64th of a beat. However, for a petasti extended by a clasma, (see p. 3 of [VespersB.pdf](http://music.samonastery.org/VespersB.pdf) [the thirty-seventh pages in the PDF] and p. 40 of [Veseprs.pdf](http://music.samonastery.org/Vespers.pdf)) the minim is split into two quavers (eighth notes), the second one note higher, and a crotchet (quarter note).
So I suspect that Papa Ephraim actually meant that the petasti to be broken into four equal quarters, all slurred, the first and the latter two all on the note indicated by the petasti (i.e. one note higher than the previous note); the second quarter is played one note higher than the others. This solution seems to equate with how it is sung and taught by the Greeks.

**Comment by danielgarthur** [comment] 2024-04-13 03:36
For the purpose of full transparency, it's unlikely that I will prioritize audio playback ornamentations any time soon as I want to focus on the scorewriting features. However, I'm not opposed to pull requests.

[BZQ ](https://bzquality.wordpress.com/) currently supports importing Neanes `byzx` files and will play back the files using samples of male choir voices. You can also configure more or less ornamentation in the playback. Any feature in Neanes that added ornamentation would ideally have some sort of similar configuration to turn them on or off, or possibly even support multiple interpretations or interpretations based on melodic context.

**Comment by mattsmi** [comment] 2024-04-13 04:50
Thanks, Daniel. I'll have to try BZQ, when I get a chance to use a Windows computer. Am using Linux for work and home.

It does not seem to want to work on wine.

**Comment by basil** [comment] 2024-04-13 07:42
@mattsmi It’s great to see that you’re another Linux user. It would also be great to see you contribute some patches to this repository.

**Comment by mattsmi** [comment] 2024-04-13 08:42
If only I could, @basil ! Apart from examples for the RTL, I think the coding is beyond me.

**Comment by basil** [comment] 2024-04-13 16:48
> If only I could, […] I think the coding is beyond me.

https://github.com/mattsmi 👀

**Comment by basil** [comment] 2024-04-21 19:32
Duplicate of #464

**Closed by basil** 2024-04-21 19:32 UTC
Labels: Type: Feature, Component: Audio
