### ISSUE TITLE
Important Request

### ISSUE THREAD

**Issue by Fotiyos** [neanes/neanes#839] opened 2024-07-13 20:53 UTC
**Is your feature request related to a problem? Please describe.**
I want to export my projects as a MIDI file, so that people who are not familiar with the Byzantine notation can know what my composition sounds like.

**Describe the solution you'd like**
I would like you to add a "export as" option in the file tab.

**Describe alternatives you've considered**
If it exists, you can also recommend a converter program for byzantine notation.

**Additional context**
Thank you in advance, your software is so beneficial for our choir.

**Comment by basil** [comment] 2024-07-13 20:55
Duplicate of #77

**Closed by basil** 2024-07-13 20:55 UTC
Labels: Type: Feature
