### ISSUE TITLE
[BUG] compounding neume behaviour inconsistent in RTL mode.

### ISSUE THREAD

**Issue by mattsmi** [neanes/neanes#568] opened 2024-03-12 18:03 UTC
**This bug was found in 0.4.18.**

- [x] Desktop

**Describe the bug**
Selecting most neumes and then choosing Heteron or Homalon shows the combining character moving forward between the selected base neume and the following one. This is the same behaviour as found in LTR mode, which I presume is the desired behaviour.

However, selecting a Kentimata sends the combining neume backwards in RTL mode, not forwards.

**To Reproduce**
Steps to reproduce the behaviour:

1. Select a Kentimata in a RTL score.
2. Choose the Hetaron.
3. You will note it goes backwards.

**Expected behaviour**
That it connects forwards whether the score is in RTL or LTR mode.

**Screenshots or files**
[naughty kentimata.zip](https://github.com/neanes/neanes/files/14576721/naughty.kentimata.zip)

See movie file [attached.](url)

**Comment by danielgarthur** [comment] 2024-03-12 18:47
I think the issue is that the kentimata should not accept either homalon or heteron. The normal Neanes font purposely does not contain anchor points on the kentimata for either the homalon or the heteron, but Neanes allows users to press the button anyway (a bug). This results in the the heteron/homalon appearing in a default location, chosen by the browser.

See, for example, Basilios Psilacos's Byzantine Ecclesiastical Music (p. 112):

> It does not accept chronic characters for increasing its time, nor
the expression characters. 

I've flipped through several books and have not yet found a counter-example. So it seems like the bug is that the homalon and heteron buttons should be disabled for kentimata.

**Comment by danielgarthur** [comment] 2024-03-12 18:54
Naturally, I found a counter-example a few minutes later... In the Anoixantaria by Phokaeus. 
<img width="93" alt="image" src="https://github.com/neanes/neanes/assets/4132779/944381dc-9f00-4ea2-aaee-4530e021cd3e">

So I'll have to fix both fonts.

**Comment by ilizol** [comment] 2024-03-12 19:20
@danielgarthur Please check this issue #5.

**Comment by danielgarthur** [comment] 2024-03-12 19:57
> @danielgarthur Please check this issue #5.

Thanks! I thought it sounded familiar. I'm pretty sure I went through the same process last time, too. That's why I had the hunch to check the Anoixantaria.

**Comment by basil** [comment] 2024-03-12 20:30
The example above is a common gesture, occuring for example in the first two of the slow Plagal Fourth Mode Resurrectional Stichera at "Lord, I have cried", the beginning of the late December Plagal Fourth Mode Doxastikon "Blood and fire...", the end of the November 21 Plagal Fourth Mode Doxastikon "After thou wast born...", as well as some settings of the Second Mode "God is the Lord".

It can be written either as a two-beat oligon or a one-beat apostrophos followed by a one-beat kentimata, which is an analytical expansion of the former. Either way it is followed by a petasti with ison and then two apostrophoi (with gorgon on the second). Also sometimes there is a third variation, a three-beat oligon followed by two apostrophoi (with gorgon on the second).

In the first case the two-beat oligon is always connected with an heteron to the petasti with ison. In the second case there is some inconsistency, with some exegetes using a connecting heteron between the kentimata and the petasti with ison and some exegetes omitting it. Phokaeus usually uses the connecting heteron in the second case, but even in his _Anastasimatarion_ he omits it in the Second Mode "God is the Lord." Peter Byzantius and John the Protopsaltis omit the connecting heteron in the second case in their respective _Anastasimataria_. Ioannis Arvanitis uses a connecting heteron on the last page [here](https://analogion.com/forum/index.php?threads/%CE%94%CE%BF%CE%BE%CE%B1%CF%83%CF%84%CE%B9%CE%BA%CE%AC-%CE%91%CE%BD%CE%B1%CE%BA%CE%BF%CE%BC%CE%B9%CE%B4%CE%AE%CF%82-%CE%91%CE%B3-%CE%A3%CF%84%CE%B5%CF%86%CE%AC%CE%BD%CE%BF%CF%85-%CE%99-%CE%91%CF%81%CE%B2%CE%B1%CE%BD%CE%AF%CF%84%CE%B7%CF%82.18694/).

My take is as follows. The rule about the kentimata not accepting "expression" characters usually applies in the general case, but this is an exception where it doesn't apply. Since the unexpanded form always takes a connecting heteron, I think using a connecting heteron on the analytical expansion can be justified on the grounds that it isn't applying (physically) to the analytical expansion but rather (logically) to the original unexpanded form. So like Phokaeus and Arvanitis, I use the connecting heteron here, and I would like for the software to support it.

**Comment by mattsmi** [comment] 2024-03-12 22:59
Supporting your quotation from Psilacos, the very same content is expressed by Chrysanthos in his great work (p. 59).

The music I was transcribing was written in the late 1800s or the very early 1900s. I don't know whether it was a custom at the time, but I do understand that Mitri el-Murr (the composer) was accomplished in his knowledge of Byzantine chant.

Perhaps @basil is correct in that both Chrysanthos and Psilacos mention the general case, but there are valid exceptions, especially where a single syllable extends over several beats/neumes.

**Comment by danielgarthur** [comment] 2024-03-13 01:13
Fixed in [0.4.19](https://github.com/neanes/neanes/releases/tag/v0.4.19).

**Closed by danielgarthur** 2024-03-13 01:13 UTC
Labels: bug
