### ISSUE TITLE
[ENHANCEMENT] More quality characters from 'EZ' font

### ISSUE THREAD

**Issue by neobabis** [neanes/neanes#570] opened 2024-03-13 23:19 UTC
**New quality characters**
The 'EZ Psaltica' from the St. Anthony's Greek Orthodox Monastery also has these quality characters that are extremely useful to add to the app:

- τρομικόν (tromikon)
- παρακλητική (paraklitiki)
- λύγισμα (lygisma)
- εκστρεπτρόν (ekstrepton)
- πίασμα (piasma)
- τσάκισμα (tsakisma)
also 'oxeia'

![newSymbols](https://github.com/neanes/neanes/assets/48261152/64de2fdf-d495-421a-bf36-396189dcad47)

**Comment by danielgarthur** [comment] 2024-03-14 01:14
Duplicate of #425

**Closed** 2024-03-14 01:14 UTC
Labels: duplicate, enhancement
