### ISSUE TITLE
[ENHANCEMENT] Right-to-left support

### ISSUE THREAD

**Issue by mattsmi** [neanes/neanes#518] opened 2024-02-26 17:18 UTC
Is it possible for Neanes to support Arabic input. This would require both the text/lyrics and the Byzantine chant neumes to be entered and displayed from right to left, rather than left to right (which supports both English and Greek texts/lyrics)?

Assume in this instance that there will be no changes requested to the neumes as had been requested in Issue 134 and its subsequent Discussion 266, both of which have disappeared.

**Comment by danielgarthur** [comment] 2024-02-26 18:00
Discussion and issue should be available here #266 #134. If you've bookmarked the links previously, those may now be broken since the project was transferred from my personal account.

**Comment by mattsmi** [comment] 2024-03-01 05:58
Daniel, I saw the release notice for 0.14.15 with RTL support. How do I enable it for the current score? I've tried all the menus and looked at all the current icons, but I cannot see how to create a RTL score.

We are preparing to teach some pieces to our choir for use in Lent and Holy Week, and this would be a great boon! Many thanks for working on it! And if you need someone to test the functionality, ... :)

**Comment by danielgarthur** [comment] 2024-03-01 05:59
@mattsmi @AlexKKhalil

I've made a first pass at supporting RTL scores in [v0.4.15](https://github.com/neanes/neanes/releases/tag/v0.4.15). I know almost nothing about Arabic and cannot read it, so it is difficult for me to test this myself. I will need to rely on you to test and report issues. When reporting them, assume that I know nothing about Arabic.

<img width="388" alt="image" src="https://github.com/neanes/neanes/assets/4132779/f157edeb-5ff7-465a-82c2-cf63c4a3ecc3">


### Instructions

1. Create a new score.
2. Open the Page Setup dialog (`File -> Page Setup`)
3. Check `Melkite RTL` in the `Miscellaneous` section
4. Click `Update` to close the dialog.
5. Click on neumes and they should appear right to left.
6. Press <kbd>Shift</kbd> + <kbd>J</kbd> to enter a tatweel. If you are at the end of a lyric box, the cursor will automatically move to the next lyric box. You can then type the next letters. You do not need to enter a tatweel at the beginning of the next lyric box. Instead, a tatweel will be added to the beginning for you whenever the previous lyric box ends with a tatweel.

### Known Issues

1. When using the Noto Naskh Arabic font, there is a space between tatweels. 
![image](https://github.com/neanes/neanes/assets/4132779/309fa2c5-af1f-48b2-b3d3-8bfca72772b5)
This space usually does not appear when using Arial or Simplified Arabic. I'm not yet sure the cause. It is, of course, possible to add an user-editable "fudge factor" that allows users to make the kashida longer or shorter based on their font choice, but I would like to first investigate whether there is any automatic way to correct it.
2. When reversing the neumes with kentimata, I may have messed up the positioning of some supporting neumes like yfesis, diesis, etc. Let me know if you see issues.
3. For some reason, if you are in a lyric box, and hold shift and press left or right, the text highlights in reverse. But inside of a textbox, the highlight direction is correct. I'm still trying to figure that one out.

**Comment by danielgarthur** [comment] 2024-03-01 06:02
By the way, is there any online resource that you could point me to that contains 

- liturgical texts in Arabic
- RTL Arabic scores 

I do not know how to search the internet in Arabic and this would help me to test myself by trying to duplicate scores.

**Comment by danielgarthur** [comment] 2024-03-01 06:06
Another question: what is a reasonable font size for Arabic lyrics? To me it looks microscopic at the default 12pt size, but that could just be because of my unfamiliarity with the script.

**Comment by mattsmi** [comment] 2024-03-01 06:09
I'll have a go a writing a Troparion and check it out now. Thanks for the instructions: I hadn't noticed that the File Set-up scrolled beyond the first screen! :(

Is there an email or something to which I can send you a link? I can upload a PDF of one of our liturgical books. It is not for public access, but should be fine for these purposes.

**Comment by mattsmi** [comment] 2024-03-01 06:14
I can post the Anistaimatarion (music for the eight modes for Vespers and Orthros).

**Comment by mattsmi** [comment] 2024-03-01 06:18
I notice as I type that it does not seem to be picking up the current note correctly. When I type LTR and go up three from Ni, the bottom right of the screen shows Ga. The RTL page is not; right from the beginning. Perhaps it is not picking up the initial martyria (Mode Key)?

**Comment by danielgarthur** [comment] 2024-03-01 06:29
> I notice as I type that it does not seem to be picking up the current note correctly. When I type LTR and go up three from Ni, the bottom right of the screen shows Ga. The RTL page is not; right from the beginning. Perhaps it is not picking up the initial martyria (Mode Key)?

Could you send a screenshot?

As for contact, Github doesn't have a private message feature anymore and I'd rather not post my email on the internet. But I am on [Element](https://app.element.io/) under the same username as my Github username.

**Comment by mattsmi** [comment] 2024-03-01 06:38
![res-trop8 ar NEANES RTLar-1](https://github.com/neanes/neanes/assets/6654733/8b2666b5-57d0-4c7e-acd9-887ff061b1dc)
ِ
Attached the Resurrectional Troparion in the 8th tone, which I've just typed in. Play back works which is great!

1. How do I insert a stavros (cross)? I could not get the button to work whether I had selected a note or just an empty spot. In the end, I've added a plus-sign as text so that the music reads correctly, but of course this is ignored in the play back.
2. How do I change the font of the lyrics? I'd prefer Amiri (the best for Arabic; vastly improved on Microsoft's Traditional Arabic) or even Scheherazade New, which is a great new font that makes things a little more easily read.
3. Yes, The size of the font is very small. It would make it hard to read from the analogion (choir stand).

**Comment by mattsmi** [comment] 2024-03-01 06:43
Attached the screenshot. It appears to be a factor of the 0.4.15 version. I'm sure that yesterday when I was writing some scores it showed correctly on the first note (Ga, rather than Ni). But I now cannot get 0.4.14 to work. Perhaps installing the newer one updated something? Or I mistook something yesterday.

![new RTL showing incorrect note](https://github.com/neanes/neanes/assets/6654733/02746708-de8d-4ac5-935d-451a933c1b44)

**Comment by danielgarthur** [comment] 2024-03-01 06:49
> ![res-trop8 ar NEANES RTLar-1](https://github.com/neanes/neanes/assets/6654733/8b2666b5-57d0-4c7e-acd9-887ff061b1dc)
> ِ
> Attached the Resurrectional Troparion in the 8th tone, which I've just typed in. Play back works which is great!
> 
> 1. How do I insert a stavros (cross)? I could not get the button to work whether I had selected a note or just an empty spot. In the end, I've added a plus-sign as text so that the music reads correctly, but of course this is ignored in the play back.
> 2. How do I change the font of the lyrics? I'd prefer Amiri (the best for Arabic; vastly improved on Microsoft's Traditional Arabic) or even Scheherazade New, which is a great new font that makes things a little more easily read.
> 3. Yes, The size of the font is very small. It would make it hard to read from the analogion (choir stand).
> 
> 

1. It's a little confusing because there are two Stavros buttons. The one you are looking for is in the left neume selector panel in the first column. The button in the toolbar is only used for one special case where the Stavros can be placed above a running elation.
2. In the Page Setup dialog you can change the font to any font installed on your computer. You can change the size there too.

**Comment by danielgarthur** [comment] 2024-03-01 06:51
> Attached the screenshot. It appears to be a factor of the 0.4.15 version. I'm sure that yesterday when I was writing some scores it showed correctly on the first note (Ga, rather than Ni). But I now cannot get 0.4.14 to work. Perhaps installing the newer one updated something? Or I mistook something yesterday.
> 
> ![new RTL showing incorrect note](https://github.com/neanes/neanes/assets/6654733/02746708-de8d-4ac5-935d-451a933c1b44)
> 

Isn't Ni the correct note? The mode key indicates Ga as the starting note, and the first note descends by three to Ni.

**Comment by mattsmi** [comment] 2024-03-01 07:32
Yes, you are right! I'm sorry, for a moment I was confused. Neanes is showing the correct notes. Sorry for the confusion!

**Comment by mattsmi** [comment] 2024-03-01 07:34
I have changed the font to Amiri and increased it to 14, also changed the colour to Navy Blue so that the lyrics are distinguished from the Byzantine neumes better.

![Uploading res-trop8 ar NEANES RTLar-1.png…]()

**Comment by mattsmi** [comment] 2024-03-01 21:38
Resending the screenshot.

![res-trop8 ar NEANES RTLar-1](https://github.com/neanes/neanes/assets/6654733/0df8cd07-6180-428e-835b-d727160e89e8)

**Closed** 2024-03-05 03:55 UTC
Labels: enhancement
