### ISSUE TITLE
Keyboard shortcuts not working on macOS

### ISSUE THREAD

**Issue by neobabis** [neanes/neanes#557] opened 2024-03-11 14:24 UTC
**This bug was found in**

- [x] MacBook
- [ ] Web App
- [ ] Both

**The bug**
Keyboard shortcuts, like Copy (⌘C) + Paste(⌘V) for Neumes, Text Box content etc, are not working in the MacBook. Conversely, they work correctly in the Web version.

**Desktop Version:**
- OS: MacOS Sonoma 14.2.1
- Neanes Version: 0.4.17

If you want more details about my system, I'm here..

**Comment by danielgarthur** [comment] 2024-03-11 20:16
I wasn't able to reproduce this on Ventura, so it may be unique to Sonoma (which I don't have access to).

**Comment by PsaltyDog** [comment] 2024-03-16 14:39
> I wasn't able to reproduce this on Ventura, so it may be unique to Sonoma (which I don't have access to).

I'm also not able to reproduce this running Neanes 0.4.17 on Sonoma 14.4.

**Comment by danielgarthur** [comment] 2024-04-02 01:50
I've upgraded to Sonoma and I was able to partially reproduce this. I can copy and paste neumes via keyboard shortcuts, but I cannot copy and paste text inside of a text box or lyric box unless I use the file menu. So there is at least a work around.

**Comment by danielgarthur** [comment] 2024-04-02 02:12
I found a couple of electron issues that suggest it may have been around for a long time and just never noticed before.

https://github.com/electron/electron/issues/18365
https://github.com/electron/electron/issues/1902

I'm not sure what do yet since I don't want to re-introduce the issue caused by https://github.com/electron/electron/issues/3682.

**Comment by pabaxe** [comment] 2024-07-02 06:51
I can also confirm this bug is occuring to me, running on M1, Sonoma 14.5.

**Comment by danielgarthur** [comment] 2024-07-03 02:31
This should be fixed in [0.4.43](https://github.com/neanes/neanes/releases/tag/v0.4.43). I do not have a Mac right now to test it, so if someone can confirm that this is fixed, I will close it.

**Comment by pabaxe** [comment] 2024-07-03 07:28
Confirmed, copy-pasting now works fine!

**Comment by pabaxe** [comment] 2024-07-04 13:31
To update this, copy pasting works only on text-boxes. Pasting on headers still is not working, also copying-pasting neumes-lyrics is still not functional.

**Comment by danielgarthur** [comment] 2024-07-04 16:08
@pabaxe On Sonoma 14.5, I was able to find several issues. 

- Copy/paste in Header/footer doesn't work
- Cmd+A does not select all

But I did not have any issues with neume lyrics. Could you describe what you saw there? Maybe there is a misunderstanding about how copy/paste works for lyrics?

**Comment by danielgarthur** [comment] 2024-07-04 16:28
Fixed in [0.4.45](https://github.com/neanes/neanes/releases/tag/v0.4.45).

**Closed by danielgarthur** 2024-07-04 16:28 UTC
Labels: Type: Bug, Component: Electron
