### ISSUE TITLE
Early neumes

### ISSUE THREAD

**Issue by pabaxe** [neanes/neanes#809] opened 2024-07-04 06:28 UTC
It would be really great if early neumes (oxeia, isaki, lygisma, tsakisma etc.) could be included along with the current ones. 
As far as I know the Stathis Series font has them included as "Stathis Palaia". If you want I can upload the file. 
Right now I'm using another software to write neumes when those early characters must be included, but Neanes is much seamless in writing and correcting. Thank you!

**Comment by basil** [comment] 2024-07-04 14:57
Duplicate of #425

**Closed by basil** 2024-07-04 14:57 UTC
Labels: Type: Feature
